### PR TITLE
Issue 23

### LINKED ISSUE #23: Split data query timer for HLS S30 and HLS L30
The data_query_timer queries both HLS S30 and HLS L30 types in a single script and it always ingested HLS L30 types first, so the  download timer won't download HLS S30 until the HLS L30 data download is done. The query timer needs to be split to two separate times for S30 and L30 types.

Rename data_subscriber timer and shell script
- data_query_timer -> hlsl30_query_timer & hlss30_query_timer
- data_download_timer -> hls_download_timer
- daac_data_subscriber_download.sh -> hls_download.sh
- daac-data_subscriber_query.sh -> hlsl30_query.sh & hlss30_query.sh

Add following log messages into the end of query log 
- number of files found to download
- number of files skipped (non-required bands)
- number of files ingested to download
- Range of data query: begin time & end time

### PR DESCRIPTION
**Pull request by maseca**
Closes #23

### CODE REVIEW

**Comment by maseca** [comment]
@hhlee445 I believe I have fixed the error you were encountering

**Comment by hhlee445** [comment]
@maseca I'm still getting an error.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Duplicate resource "aws_cloudwatch_log_group" configuration
│ 
│   on ../modules/common/main.tf line 2118:
│ 2118: resource "aws_cloudwatch_log_group" "hlsl30_query_timer" {
│ 
│ A aws_cloudwatch_log_group resource named "hlsl30_query_timer" was already declared at ../modules/common/main.tf:2087,1-57. Resource names must be unique per type in each module.
╵

**Comment by maseca** [comment]
@hhlee445 Please check again

**Comment by hhlee445** [comment]
@maseca hlsl30_query job failed with following error.

```
##########################################
Running job to query LPDAAC HLSL30 data
Mon May  2 19:12:07 UTC 2022
python /home/ops/verdi/ops/opera-pcm/data_subscriber/daac_data_subscriber.py -m 60 -c HLSL30 -s opera-dev-isl-fwd-hyunlee -e L30 --index-mode query
INFO:root:Log level set to INFO
INFO:root:sys.argv = ['/home/ops/verdi/ops/opera-pcm/data_subscriber/daac_data_subscriber.py', '-m', '60', '-c', 'HLSL30', '-s', 'opera-dev-isl-fwd-hyunlee', '-e', 'L30', '--index-mode', 'query']
Traceback (most recent call last):
  File "/home/ops/verdi/ops/opera-pcm/data_subscriber/daac_data_subscriber.py", line 480, in <module>
    run()
  File "/home/ops/verdi/ops/opera-pcm/data_subscriber/daac_data_subscriber.py", line 83, in run
    downloads, temporal_range = query_cmr(args, token, CMR)
  File "/home/ops/verdi/ops/opera-pcm/data_subscriber/daac_data_subscriber.py", line 265, in query_cmr
    temporal_range = get_temporal_range(args.startDate, args.endDate,
  File "/home/ops/verdi/ops/opera-pcm/data_subscriber/daac_data_subscriber.py", line 302, in get_temporal_range
    raise ValueError("One of start-date or end-date must be specified.")
ValueError: One of start-date or end-date must be specified.
Failed to run daac_data_subscriber.py
Mon May  2 19:12:10 UTC 2022
```

**Pull request merged**
