### PR TITLE
Issue 75

### LINKED ISSUE #75: [New Feature]: Use different queue for data download jobs and data_query_timer_trigger_frequency variable for query
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

Data download jobs were using 'opera-job_worker-small' queue which is used by PGE jobs. Data download was not occurring while the PGE jobs are executing.

### Describe the feature request

1. Use different queue for the data download and PGE job execution.

2. Use _data_query_timer_trigger_frequency_ variable to execute daac_data_subscriber_quey.sh as -m option

### PR DESCRIPTION
**Pull request by maseca**
Closes #75 
See also: https://github.com/nasa/opera-sds-lambdas/pull/6

### CODE REVIEW

**Comment by hhlee445** [comment]
@maseca I was able to finish cluster provisioning, however, it throws an error. Here is a snapshot from Figaro UI
Screen Shot 2022-05-10 at 8 32 19 AM

**Comment by maseca** [comment]
Hey @hhlee445 , could you please check via "View Job" for any additional error information in the script output?

**Comment by hhlee445** [comment]
https://s3.console.aws.amazon.com/s3/buckets/opera-dev-triage-fwd-hyunlee?region=us-west-2&prefix=triaged_job-data-subscriber-download-timer-20220510T233900_20220510T234900-20220510T234941.223666Z_task-e6ec66e3-bffb-413c-bc7a-eb84058f49cd/&showversions=false

**Comment by maseca** [comment]
Thanks, I pushed a fix.

**Comment by hhlee445** [comment]
@maseca https://github.com/nasa/opera-sds-pcm/blob/issue_75/cluster_provisioning/modules/common/main.tf#L2121, should it be **hlss30_query_job_type**?

**Comment by hhlee445** [comment]
Still getting an error from opera-hyunlee-100-hlss30-query-timer lambda function


2022-05-12T11:29:24.896-07:00Copy[ERROR] KeyError: 'ISL_BUCKET_NAME'Traceback (most recent call last):  File "/var/task/lambda_function.py", line 100, in lambda_handler    isl_bucket_name = os.environ['ISL_BUCKET_NAME']  File "/var/lang/lib/python3.7/os.py", line 681, in __getitem__    raise KeyError(key) from None | [ERROR] KeyError: 'ISL_BUCKET_NAME' Traceback (most recent call last):   File "/var/task/lambda_function.py", line 100, in lambda_handler     isl_bucket_name = os.environ['ISL_BUCKET_NAME']   File "/var/lang/lib/python3.7/os.py", line 681, in __getitem__     raise KeyError(key) from None
-- | --

**Comment by maseca** [comment]
@hhlee445 I pushed a fix for the job type typo. Are you using the lambda code from https://github.com/nasa/opera-sds-lambdas/pull/6 ? You may have to copy paste it into the AWS console until the changes are on Artifactory.

**Pull request merged**
