### PR TITLE
Issue 108

### PR DESCRIPTION
**Pull request by hhlee445**

### CODE REVIEW

**Comment by maseca** [comment]
Closes #108

**Comment by maseca** [comment]
Note: OPS and UAT endpoint products are incompatible and any attempt to download a product from the wrong endpoint will result in an error

**Review by hhlee445 — COMMENTED** [review]
It queries successfully and ingests into hls_catalog and hls_spatial_catalog, however, it doesn't submit download job. Don't we need to pass --endpoint to trigger download job (submit_download_job)?

**Comment by maseca** [comment]
Tested on Mozart with CLI and in browser on demand

**Pull request merged**
